### ISSUE TITLE
IE11 cannot recognize Promise 

### ISSUE THREAD

**Issue by Band-Aid** [box-community/box-javascript-sdk#25]
It looks like babel is missing the reference to polyfill
An alternative is to add [transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime/) to .babelrc

**Comment by Band-Aid** [comment]
#27

**Comment by Band-Aid** [comment]
There's couple problems with the method uploadNewFileVersion and preflight
IE is not compatible with Formdata.get() and cannot get the id parameter 

 options.fileId = options.body.get("id") || options.body.get("fileId") || options.body.get("file_id");

AFAIK this is the only place it's using the .get method to obtain the File id.
Is there a reason we are doing this and why can't we access the property directly instead of use the .get method.

I tried adding formdata-polyfill to babel but it sometimes doesn't work (hence closer of the pull request) #27 

Can we consider a better way to handle accessing the property?

**Comment by allenmichael** [comment]
potentially could just do an `options.fileId = options.id || options.body.get("id") || options.body.get("fileId") || options.body.get("file_id");`

i don't have an environment with IE11, would you mind checking on if that works?

**Comment by Band-Aid** [comment]
@allenmichael Thanks for the advice, just a quick update, I tried your suggestion but it did not work :(
I will try and troubleshoot this further.

**Comment by Band-Aid** [comment]
implemented -> `options.fileId = options.id || options.body.get("id") || options.body.get("fileId") || options.body.get("file_id");`
