### ISSUE TITLE
Restrict number of parallel uploads for chunked uploads

### ISSUE THREAD

**Issue by cbetta** [box-community/box-javascript-sdk#30]
Currently the chunked upload manager tries to upload all chunks at once, generating quite a browser load for very large files. It would be cool if the manager could be configured to only upload X parts at a time.

**Comment by allenmichael** [comment]
I'm not sure it's the best design to limit this in code with JS. From my understanding, the browser itself will control how many concurrent XHR calls it can make efficiently. I think the overhead of creating a JS queue would be extra, unnecessary code to maintain, and it's likely better to let the individual browsers maintain their queue of work based on their own parallel XHR limits. I could be totally wrong here, so I'm open to suggestion.

**Comment by cbetta** [comment]
Ah, I am not sure how this is currently handled in your code tbh. I thought it would just try and create as many uploads as needed, but I see your point that the browser indeed seems to limit this. 

The only reason why I brought this up was because my laptop seemed to take off when I tried to upload a 3GB file, and I was worried this experience would bring a lesser laptop to a halt.
